### ISSUE TITLE
buildhub2 doesn't run in local dev environment

### ISSUE THREAD

**Issue by willkg** [mozilla-services/buildhub2#584]
Buildhub doesn't run in the local dev environment. I'm hitting a bunch of problems. This issue covers fixing things so we can run it locally.

**Comment by willkg** [comment]
First, the ui isn't proxying web requests. I think it's because it's set to proxy to localhost:8000 which doesn't exist in the ui container. Changing "proxy" to "http://web:8000" fixes that.

Second, I'm hitting this assertion error in the web container:

```
eb_1            | ERROR 2019-05-31 15:02:01,454 django.request Internal Server Error: /sockjs-node/357/mrp440zw/websocket
web_1            | Traceback (most recent call last):
web_1            |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
web_1            |     response = get_response(request)
web_1            |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
web_1            |     response = self.process_exception_by_middleware(e, request)
web_1            |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 124, in _get_response
web_1            |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
web_1            |   File "/app/buildhub/urls.py", line 30, in serve
web_1            |     assert os.path.isdir(document_root), document_root
web_1            | AssertionError: /app/ui/build
web_1            | ERROR 2019-05-31 15:02:01,455 django.server "GET /sockjs-node/357/mrp440zw/websocket HTTP/1.1" 500 71239
```

That directory gets created when building the image, but because it's in `/app` and `/app` is volume mounted repo directory, there's no `/app/ui/build` in the repo and then it fails. We had this problem with Socorro as well and instead of building static assets in `/app`, we built them in another directory outside of `/app`.

Another way to deal with this is to have the run script build the static assets if they don't exist and then run the web. I think I may do that here.

**Comment by willkg** [comment]
`bin/build-ui.sh` suggests we don't need to build the ui at all since it's handled by the ui container and that we just need an empty `build/` directory. I'm just going to go with that.
